# code: language=ansible

---
- hosts: all
  become: true
  become_user: root
  tasks:
    #- name: update apt packages
    #  apt:
    #    update_cache: yes
    #    force_apt_get: yes
    #    cache_valid_time: 3600
    - name: Update repositories cache and install "foo" package
      ansible.builtin.apt:
        name: foo
        update_cache: yes 