# code: language=ansible
    #- name: update apt packages
    #  apt:
    #    update_cache: yes
    #    force_apt_get: yes
    #    cache_valid_time: 3600


---
- hosts: all

  tasks:
    - name: Ensure the httpd service is running
      service:
        name: systemd
        state: started
      become: true